// Covers the HDRI backdrop path with assets actually present, which the
// asset-free run in view-lighting.mjs cannot reach: PMREM lighting from a real
// .hdr, an equirectangular backdrop, the headroom from meta.json coming back
// through backgroundIntensity, and the rotation control turning it.
//
// The fixtures are generated by tools/hdri-prep.mjs itself and served from a
// temporary public directory, so the repository's own public/assets is neither
// read nor written and the test behaves the same whether or not the user has
// committed real HDRIs.
import { chromium } from '@playwright/test';
import { createServer } from 'vite';
import { cp, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { encodeBackdrop, encodeRadiance, headroom } from '../tools/hdri-prep.mjs';

// Four bright quadrants around the horizon: whatever the camera faces, the
// backdrop is visible, and rotating it moves a different colour into view.
function quadrants(width, height) {
  const data = new Float32Array(width * height * 4);
  const colours = [[3, 0.2, 0.2], [0.2, 3, 0.2], [0.2, 0.2, 3], [2.5, 2.5, 0.4]];
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const [r, g, b] = colours[Math.floor((x / width) * 4)];
      const sky = y < height / 2 ? 1 : 0.35;
      const o = (y * width + x) * 4;
      data[o] = r * sky; data[o + 1] = g * sky; data[o + 2] = b * sky; data[o + 3] = 1;
    }
  return { width, height, data };
}

const root = new URL('..', import.meta.url).pathname;
const publicDir = await mkdtemp(join(tmpdir(), 'booth-public-'));
const presetDir = join(publicDir, 'assets', 'hdri', 'warehouse');
const image = quadrants(256, 128);
const intensity = headroom(image);
await cp(join(root, 'public'), publicDir, { recursive: true });
await mkdir(presetDir, { recursive: true });
await writeFile(join(presetDir, 'light.hdr'), encodeRadiance(image));
await writeFile(join(presetDir, 'bg.jpg'), encodeBackdrop(image, { headroom: intensity }));
await writeFile(join(presetDir, 'meta.json'), JSON.stringify({ backgroundIntensity: intensity, credit: 'synthetic fixture' }));

const server = await createServer({ root, publicDir, server: { host: '127.0.0.1', port: 5191 } });
await server.listen();
const browser = await chromium.launch({
  headless: true,
  ...(process.env.BOOTH_TEST_CHROMIUM ? { executablePath: process.env.BOOTH_TEST_CHROMIUM } : {}),
  args: ['--no-sandbox', '--enable-unsafe-swiftshader', '--use-angle=swiftshader', '--use-gl=angle', '--in-process-gpu', '--single-process', '--disable-dev-shm-usage'],
});
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], warnings = [];
  page.on('pageerror', (e) => errors.push(e.stack || e.message));
  page.on('console', (m) => { if (m.type() === 'warning' || m.type() === 'error') warnings.push(m.text()); });
  await page.goto('http://127.0.0.1:5191');
  await page.waitForFunction(() => !!window.__booth?.scene);

  // The asset files have to be reachable at the paths the presets name, or
  // every assertion below would pass on the procedural fallback instead.
  assert.equal((await page.request.head('http://127.0.0.1:5191/assets/hdri/warehouse/light.hdr')).status(), 200);

  await page.click('[data-tab="layout"]');
  await page.selectOption('select[aria-label="Environment"]', 'warehouse');
  await page.waitForFunction(() => !!window.__booth.scene.scene.environment, null, { timeout: 15000 });

  const applied = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return {
      environment: !!s.environment?.isTexture,
      background: !!s.background?.isTexture,
      mapping: s.background?.mapping,
      equirect: s.background?.mapping === 303, // EquirectangularReflectionMapping
      colorSpace: s.background?.colorSpace,
      intensity: s.backgroundIntensity,
      fog: s.fog,
      exposure: window.__booth.scene.renderer.toneMappingExposure,
    };
  });
  assert.equal(applied.environment, true, 'the .hdr reached scene.environment through PMREM');
  assert.equal(applied.background, true, 'the .jpg reached scene.background');
  assert.equal(applied.equirect, true, `backdrop mapping ${applied.mapping} is not equirectangular`);
  assert.equal(applied.colorSpace, 'srgb', 'the backdrop is decoded as sRGB');
  assert.equal(applied.fog, null, 'procedural fog would sit in front of a photographed backdrop');
  assert.equal(applied.intensity, intensity, 'meta.json headroom is multiplied back in');
  assert.equal(applied.exposure, 1, 'the trade show preset sets its own exposure');

  // Rotation: the same control a user panorama uses now turns a preset backdrop.
  const rotation = page.locator('input[aria-label="Pan · horizontal"]');
  assert.equal(await rotation.count(), 1, 'a preset with a backdrop offers rotation');
  await rotation.fill('90');
  await rotation.dispatchEvent('change');
  await page.waitForFunction(() => Math.abs(window.__booth.scene.scene.backgroundRotation.y - Math.PI / 2) < 1e-6, null, { timeout: 5000 });
  const turned = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return { y: s.backgroundRotation.y, background: !!s.background?.isTexture, intensity: s.backgroundIntensity };
  });
  assert.ok(Math.abs(turned.y - Math.PI / 2) < 1e-6, 'the backdrop turned with the control');
  assert.equal(turned.background, true, 'the backdrop survived the re-render');
  assert.equal(turned.intensity, intensity, 'headroom survived the re-render');

  // Backdrop framing. A spherical photograph is framed by field of view alone,
  // so the backdrop is drawn in its own pass through a wider lens. Three things
  // have to hold: the wider lens is actually used, the booth keeps its own
  // 62-degree perspective, and scene.background survives a pass that borrows it.
  const framing = page.locator('input[aria-label="Backdrop zoom"]');
  assert.equal(await framing.count(), 1, 'a preset with a backdrop offers framing');
  const framed = await page.evaluate(() => {
    const view = window.__booth.scene;
    view.renderFrame();
    return {
      backdropFov: view.backdropCamera.fov,
      cameraFov: view.camera.fov,
      restored: !!view.scene.background?.isTexture,
      borrowed: view.backdropScene.background,
    };
  });
  assert.equal(framed.cameraFov, 62, 'the booth keeps its own field of view');
  assert.ok(
    framed.backdropFov > 80 && framed.backdropFov < 90,
    `the backdrop should be drawn near 85 degrees, got ${framed.backdropFov}`,
  );
  assert.equal(framed.restored, true, 'the backdrop pass put scene.background back');
  assert.equal(framed.borrowed, null, 'the backdrop pass does not hold the texture between frames');

  // Tilt is the second aiming axis. Pan is still at 90 degrees from above, so
  // this also pins the Euler order: under the default XYZ a pan-then-tilt rolls
  // the horizon, and YXZ is what keeps the hall level.
  const tilt = page.locator('input[aria-label="Tilt · vertical"]');
  assert.equal(await tilt.count(), 1, 'a preset with a backdrop offers tilt');
  await tilt.fill('30');
  await tilt.dispatchEvent('change');
  await page.waitForFunction(
    () => Math.abs(window.__booth.scene.scene.backgroundRotation.x - Math.PI / 6) < 1e-6,
    null,
    { timeout: 5000 },
  );
  const aimed = await page.evaluate(() => {
    const view = window.__booth.scene;
    view.renderFrame();
    const s = view.scene;
    return {
      x: s.backgroundRotation.x,
      y: s.backgroundRotation.y,
      order: s.backgroundRotation.order,
      backdropOrder: view.backdropScene.backgroundRotation.order,
      roll: s.backgroundRotation.z,
    };
  });
  assert.ok(Math.abs(aimed.x - Math.PI / 6) < 1e-6, 'the backdrop tilted with the control');
  assert.ok(Math.abs(aimed.y - Math.PI / 2) < 1e-6, 'tilt left the pan alone');
  assert.equal(aimed.roll, 0, 'aiming the backdrop never rolls the horizon');
  assert.equal(aimed.order, 'YXZ', 'pan-then-tilt order keeps the horizon level');
  assert.equal(aimed.backdropOrder, 'YXZ', 'the backdrop pass inherits the same order');

  // The pole limit the assertions below share, restated from src/scene.js.
  const view_edge_limit = 52;

  // Horizon lock. The backdrop's wider lens compresses the same pitch, so a
  // locked backdrop camera has to be pitched further than the real one for the
  // photographed horizon to stay nailed to the floor. Off, the two match and
  // the horizon drifts, which is the behaviour the toggle turns back on.
  const pitched = await page.evaluate(() => {
    const view = window.__booth.scene;
    const read = () => {
      // A gentle tilt: past about 20 degrees the lens is already at the pole
      // limit and the backdrop falls back to the camera's own, where there is
      // nothing to correct. See BACKDROP_EDGE_LIMIT.
      view.camera.position.set(3.2, 1.5, 3.2);
      view.controls.target.set(0, 2.0, 0);
      view.camera.lookAt(view.controls.target);
      view.controls.update();
      view.renderFrame();
      const euler = (q) => {
        const e = new (Object.getPrototypeOf(view.scene.backgroundRotation).constructor)();
        return e.setFromQuaternion(q, 'YXZ').x;
      };
      return {
        camera: euler(view.camera.quaternion),
        backdrop: euler(view.backdropCamera.quaternion),
        fov: view.backdropCamera.fov,
        cameraFov: view.camera.fov,
      };
    };
    view.backdropLock = true;
    const locked = read();
    view.backdropLock = false;
    const loose = read();
    view.backdropLock = true;
    return { locked, loose };
  });
  assert.ok(Math.abs(pitched.locked.camera) > 0.08, `the camera should be pitched, got ${pitched.locked.camera}`);
  assert.ok(pitched.locked.fov > pitched.locked.cameraFov, 'the backdrop is still drawn through a wider lens at this tilt');
  assert.ok(
    Math.abs(pitched.locked.backdrop) > Math.abs(pitched.locked.camera) + 0.01,
    `locked backdrop pitch ${pitched.locked.backdrop} should exceed the camera's ${pitched.locked.camera}`,
  );
  assert.ok(
    Math.abs(pitched.loose.backdrop - pitched.loose.camera) < 1e-6,
    'unlocked, the backdrop simply copies the camera — the drifting horizon this toggle fixes',
  );

  // The artifact that sent this back for a second round: at 25% framing and a
  // small tilt the backdrop lens reached 135 degrees, so the top of the frame
  // sampled the equirectangular pole and came back as radial smear. The lens
  // is now bounded by how far from the horizon the frame edge lands.
  const pole = await page.evaluate(() => {
    const view = window.__booth.scene;
    const project = window.__booth.project;
    project.booth.backdropFraming = 25;
    window.__booth.mutate(() => {});
    const T = Object.getPrototypeOf(view.scene.backgroundRotation).constructor;
    const readAt = (y, ty) => {
      view.camera.position.set(0, y, 5.6);
      view.controls.target.set(0, ty, 0);
      view.camera.lookAt(view.controls.target);
      view.controls.update();
      view.renderFrame();
      const pitch = Math.abs(new T().setFromQuaternion(view.backdropCamera.quaternion, 'YXZ').x) * 180 / Math.PI;
      return { fov: view.backdropCamera.fov, edge: pitch + view.backdropCamera.fov / 2, cameraFov: view.camera.fov };
    };
    const out = { level: readAt(1.5, 1.35), tilted: readAt(2.2, 1.0), steep: readAt(3.6, 0.4) };
    // Leave the camera level: the framing screenshots below compare two lenses,
    // and at a steep tilt both fall back to the camera's own — the same frame
    // twice, which would fail for the wrong reason.
    readAt(1.5, 1.35);
    return out;
  });
  for (const [name, frame] of Object.entries(pole))
    assert.ok(
      frame.edge <= view_edge_limit + 1e-6 || frame.fov === frame.cameraFov,
      `${name}: the backdrop frame edge reached ${frame.edge.toFixed(1)}° with a ${frame.fov.toFixed(1)}° lens`,
    );
  assert.ok(pole.level.fov > pole.level.cameraFov, 'a level camera still gets the wide backdrop the framing asked for');
  assert.ok(pole.steep.fov <= pole.level.fov, 'and a steep one gets less of it, not more');

  // The framing has to reach the screen, not just the camera object.
  const canvas = page.locator('#viewport canvas, canvas').first();
  const wide = await canvas.screenshot();
  await framing.fill('100');
  await framing.dispatchEvent('change');
  await page.waitForFunction(
    () => Math.abs(window.__booth.scene.backdropFraming - 100) < 1e-6,
    null,
    { timeout: 5000 },
  );
  const matched = await page.evaluate(() => {
    const view = window.__booth.scene;
    view.renderFrame();
    return { backdropFov: view.backdropCamera.fov, background: !!view.scene.background?.isTexture };
  });
  assert.equal(matched.background, true, 'the backdrop survived the framing change');
  const tight = await canvas.screenshot();
  assert.ok(!wide.equals(tight), 'changing the framing changed the rendered frame');

  await framing.fill('65');
  await framing.dispatchEvent('change');
  await page.waitForFunction(
    () => Math.abs(window.__booth.scene.backdropFraming - 65) < 1e-6,
    null,
    { timeout: 5000 },
  );

  // Image-based lighting must not reach uploaded artwork on the default setting.
  const shielded = await page.evaluate(() =>
    [...window.__booth.scene.artGroups.values()].map((g) => g.plane.material.envMapIntensity));
  assert.ok(shielded.every((v) => v === 0), 'accurate colour still shields artwork from the HDRI');

  // Going back to a preset with no assets has to release the backdrop.
  await page.selectOption('select[aria-label="Environment"]', 'studio');
  await page.waitForFunction(() => !window.__booth.scene.scene.environment, null, { timeout: 5000 });
  const cleared = await page.evaluate(() => {
    const s = window.__booth.scene.scene;
    return { environment: s.environment, intensity: s.backgroundIntensity, rotation: s.backgroundRotation.y };
  });
  assert.equal(cleared.environment, null, 'the environment map is dropped with the preset');
  assert.equal(cleared.intensity, 1, 'headroom does not leak onto the procedural sky');
  assert.equal(cleared.rotation, 0, 'rotation does not leak onto the procedural sky');

  assert.deepEqual(errors, [], 'no page errors');
  const deprecated = warnings.filter((w) => /deprecated/i.test(w));
  assert.deepEqual(deprecated, [], 'no deprecated three.js loaders');
  console.log('PASS HDRI lighting, backdrop, headroom and rotation with real assets.');
} finally {
  await browser.close();
  await server.close();
  await rm(publicDir, { recursive: true, force: true });
}
